spring:
  datasource:
    url: "jdbc:mysql://116.62.214.253:3306/big_games?useUnicode=true&characterEncoding=utf-8&useSSL=false"
    username: "root"
    password: "liusong11"
  redis:
    database: 1
    host: 116.62.214.253
    port: 6379
    password: liusong11
server:
  port: 9090

mybatis:
    type-aliases-package: "com.spring.security.entity"
    mapper-locations: "classpath*:/mybatis/**/*Mapper.xml"